### ISSUE TITLE
PlaybackActivityTest fails with NumberFormatException

### ISSUE THREAD

**Issue by mkjensen** [mkjensen/danish-media-license#18]
The `PlaybackActivityTest` class is currently ignored because of the `NumberFormatException: For input string: ".0"` error below. I tried upgrading to Robolectric 3.1-SNAPSHOT but that broke at lot of other tests.

```
android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/activity_ondemand_playback.xml line #-1 (sorry, not yet implemented): Error inflating class fragment

	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
	at android.app.Activity.setContentView(Activity.java:2144)
	at com.github.mkjensen.dml.ondemand.PlaybackActivity.onCreate(PlaybackActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.github.mkjensen.dml.ondemand.PlaybackActivityTest.before(PlaybackActivityTest.java:48)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NumberFormatException: For input string: ".0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:128)
	at android.content.res.TypedArray.getInt(TypedArray.java:322)
	at android.animation.AnimatorInflater.setupValues(AnimatorInflater.java:470)
	at android.animation.AnimatorInflater.parseAnimatorFromTypeArray(AnimatorInflater.java:294)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:618)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:531)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:504)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:105)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:95)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:80)
	at android.support.v17.leanback.app.PlaybackOverlaySupportFragment.loadAnimator(PlaybackOverlaySupportFragment.java:369)
	at android.support.v17.leanback.app.PlaybackOverlaySupportFragment.loadBgAnimator(PlaybackOverlaySupportFragment.java:382)
	at android.support.v17.leanback.app.PlaybackOverlaySupportFragment.onCreate(PlaybackOverlaySupportFragment.java:628)
	at com.github.mkjensen.dml.ondemand.PlaybackFragment.onCreate(PlaybackFragment.java:83)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	... 34 more
```

**Comment by mkjensen** [comment]
Removed Robolectric in favor of classic instrumentation tests in https://github.com/mkjensen/danish-media-license/commit/3a273bdc28328c6853d50490a2f9ab359d6c0b58. See https://github.com/mkjensen/danish-media-license/issues/14 for more information.
