### ISSUE TITLE
SearchActivityTest fails with RuntimeException

### ISSUE THREAD

**Issue by mkjensen** [mkjensen/danish-media-license#26]
The `SearchActivityTest` class is currently ignored because of the `RuntimeException: expected com.github.mkjensen.dml:style/TextAppearance_Leanback_SearchTextEdit to be a attr, is a style` error below.

```
android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/lb_search_fragment.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v17.leanback.widget.SearchBar

	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.support.v17.leanback.app.SearchSupportFragment.onCreateView(SearchSupportFragment.java:261)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
	at android.app.Activity.setContentView(Activity.java:2144)
	at com.github.mkjensen.dml.ondemand.SearchActivity.onCreate(SearchActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.github.mkjensen.dml.ondemand.SearchActivityTest.before(SearchActivityTest.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v17.leanback.app.SearchSupportFragment.$$robo$$onCreateView(SearchSupportFragment.java:261)
	at android.support.v17.leanback.app.SearchSupportFragment.onCreateView(SearchSupportFragment.java)
	at android.support.v4.app.Fragment.$$robo$$performCreateView(Fragment.java:1974)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1036)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$addFragment(FragmentManager.java:1332)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$onCreateView(FragmentManager.java:2288)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java)
	at android.support.v4.app.FragmentController.$$robo$$onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java)
	at android.support.v4.app.FragmentActivity.$$robo$$dispatchFragmentsOnCreateView(FragmentActivity.java:357)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.$$robo$$onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:365)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$setContentView(PhoneWindow.java:377)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
	at android.app.Activity.$$robo$$setContentView(Activity.java:2144)
	at android.app.Activity.setContentView(Activity.java)
	at com.github.mkjensen.dml.ondemand.SearchActivity.onCreate(SearchActivity.java:38)
	at android.app.Activity.$$robo$$performCreate(Activity.java:5933)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.github.mkjensen.dml.ondemand.SearchActivityTest.before(SearchActivityTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more
Caused by: android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/lb_search_bar.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v17.leanback.widget.SearchEditText
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.support.v17.leanback.widget.SearchBar.__constructor__(SearchBar.java:149)
	at android.support.v17.leanback.widget.SearchBar.<init>(SearchBar.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.support.v17.leanback.app.SearchSupportFragment.onCreateView(SearchSupportFragment.java:261)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
	at android.app.Activity.setContentView(Activity.java:2144)
	at com.github.mkjensen.dml.ondemand.SearchActivity.onCreate(SearchActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.github.mkjensen.dml.ondemand.SearchActivityTest.before(SearchActivityTest.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:479)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v17.leanback.widget.SearchBar.$$robo$$__constructor__(SearchBar.java:149)
	at android.support.v17.leanback.widget.SearchBar.<init>(SearchBar.java)
	at android.support.v17.leanback.widget.SearchBar.<init>(SearchBar.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v17.leanback.app.SearchSupportFragment.$$robo$$onCreateView(SearchSupportFragment.java:261)
	at android.support.v17.leanback.app.SearchSupportFragment.onCreateView(SearchSupportFragment.java)
	at android.support.v4.app.Fragment.$$robo$$performCreateView(Fragment.java:1974)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1036)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$addFragment(FragmentManager.java:1332)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$onCreateView(FragmentManager.java:2288)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java)
	at android.support.v4.app.FragmentController.$$robo$$onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java)
	at android.support.v4.app.FragmentActivity.$$robo$$dispatchFragmentsOnCreateView(FragmentActivity.java:357)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.$$robo$$onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:365)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$setContentView(PhoneWindow.java:377)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
	at android.app.Activity.$$robo$$setContentView(Activity.java:2144)
	at android.app.Activity.setContentView(Activity.java)
	at com.github.mkjensen.dml.ondemand.SearchActivity.onCreate(SearchActivity.java:38)
	at android.app.Activity.$$robo$$performCreate(Activity.java:5933)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.github.mkjensen.dml.ondemand.SearchActivityTest.before(SearchActivityTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more
Caused by: java.lang.RuntimeException: expected com.github.mkjensen.dml:style/TextAppearance_Leanback_SearchTextEdit to be a attr, is a style
	at org.robolectric.res.ResName.mustBe(ResName.java:143)
	at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getAttrValue(ShadowAssetManager.java:451)
	at org.robolectric.shadows.ShadowResources.getOverlayedThemeValue(ShadowResources.java:292)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:137)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:472)
	at android.view.View.__constructor__(View.java:3677)
	at android.view.View.<init>(View.java)
	at android.widget.TextView.<init>(TextView.java)
	at android.widget.EditText.<init>(EditText.java)
	at android.support.v17.leanback.widget.StreamingTextView.<init>(StreamingTextView.java)
	at android.support.v17.leanback.widget.SearchEditText.<init>(SearchEditText.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.support.v17.leanback.widget.SearchBar.__constructor__(SearchBar.java:149)
	at android.support.v17.leanback.widget.SearchBar.<init>(SearchBar.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.support.v17.leanback.app.SearchSupportFragment.onCreateView(SearchSupportFragment.java:261)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
	at android.app.Activity.setContentView(Activity.java:2144)
	at com.github.mkjensen.dml.ondemand.SearchActivity.onCreate(SearchActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.github.mkjensen.dml.ondemand.SearchActivityTest.before(SearchActivityTest.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more
```

**Comment by mkjensen** [comment]
Removed Robolectric in favor of classic instrumentation tests in https://github.com/mkjensen/danish-media-license/commit/3a273bdc28328c6853d50490a2f9ab359d6c0b58. See https://github.com/mkjensen/danish-media-license/issues/14 for more information.
